name: Publish snap
description: >
  Publish a snap and its components to a channel in the Snap Store.
  
  The channel is set based on the trigger:
  - PR: <track>/edge/pr-<pr-num>
  - Not a PR: <track>/edge/<branch>

inputs:
  store-credentials:
    description: >
      The Snapcraft store credentials to use

      This parameter is required to publish a snap and
      its components to Snap Store.
    default: ''
    required: true
  snap-track:
    description: The snap channel's track
    default: 'latest'
    required: true

runs:
  using: composite
  steps:
    # Requires store credentials secret set.
    # Check README.md for steps on how to generate it and use it in workflows.
    - name: Publish snap
      shell: bash
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ inputs.store-credentials }}
      run: |
        if [ -z "$SNAPCRAFT_STORE_CREDENTIALS" ]; then
          echo "SNAPCRAFT_STORE_CREDENTIALS is not set."
          exit 1
        fi

        # Construct the snap channel
        channel_track="${{ inputs.snap-track }}"
        channel_risk="edge"

        if [ -n "${{ github.event.number }}" ]; then 
          echo "Triggered from PR: ${{ github.event.number }}"
          channel_branch="pr-${{ github.event.number }}"
        else
          echo "Triggered from branch: ${{ github.ref_name }}"
          channel_branch="${{ github.ref_name }}"
        fi

        channel="$channel_track/$channel_risk/$channel_branch"
        echo "Using channel: $channel"

        "${{ github.action_path }}/upload.sh" "$channel"
