name: Publish snap
description: >
  Publish a snap and its components to a specified channel in the Snap Store.

inputs:
  store-credentials:
    description: >
      The Snapcraft store credentials to use

      This parameter is required to publish a snap and
      its components to Snap Store.
    default: ''
    required: true
  publish-channel:
    description: The channel where the snap should be published.
    default: ''
    required: true

runs:
  using: composite
  steps:
    # Requires store credentials secret set.
    # Check README.md for steps on how to generate it and use it in workflows.
    - name: Publish snap
      shell: bash
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ inputs.store-credentials }}
      run: |
        if [ -z "$SNAPCRAFT_STORE_CREDENTIALS" ]; then
          echo "SNAPCRAFT_STORE_CREDENTIALS is not set."
          exit 1
        fi

        channel="${{ inputs.publish-channel }}"
        if [ -z "$channel" ]; then
          echo "publish-channel is not set."
          exit 1
        fi
        echo "Using channel: $channel"

        "${{ github.action_path }}/upload.sh" "$channel"
