name: Build and publish snap

on:
  workflow_call:
    inputs:
      publish-channel:
        required: true
        type: string
      init-build-script:
        description: Script to run before building the snap
        required: false
        type: string
    secrets:
      store-credentials:
        required: true

jobs:
  build:
    name: Build & publish
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, linux, amd64, xlarge, noble ]
          - [ self-hosted, linux, arm64, xlarge, noble ]
    runs-on: ${{ matrix.runner }}

    steps:
      # Update snapd as we need a recent one to support components
      - name: Update snapd
        run: |
          sudo snap refresh snapd

      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install -y git-lfs

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: true

      - name: Init build environment
        run: |
          if [ -n "${{ inputs.init-build-script }}" ]; then
            ./"${{ inputs.init-build-script }}"
          fi

      - name: Build snap
        uses: canonical/action-build@v1

      # Requires the store-credentials secret set by the calling workflow
      - name: Publish snap
        uses: ./actions/publish
        with:
          store-credentials: ${{ secrets.store-credentials }}
          publish-channel: ${{ inputs.publish-channel }}
