name: Build and publish snap

on:
  workflow_call:
    inputs:
      runner:
        description: |
          The type of machine to run the job on.
          
          The input should be a JSON string or array. For example:
          - '"ubuntu-latest"' for a single label
          - '[ "self-hosted", "amd64", "large" ]' for multiple labels

          Note: Using GH-hosted runners is currently not possible; see https://github.com/canonical/inference-snaps-dev/issues/40
        required: true
        type: string
      publish-channel:
        description: Snap Store channel for publishing the snap
        required: true
        type: string
      init-build-script:
        description: Script to run before building the snap
        required: false
        type: string
    secrets:
      store-credentials:
        description: Snap Store credentials for publishing the snap to the specified channel
        required: true

jobs:
  build:
    name: Build & publish
    runs-on: ${{ fromJSON(inputs.runner) }}

    steps:
      # Update snapd as we need a recent one to support components
      - name: Update snapd
        run: |
          sudo snap refresh snapd

      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install -y git-lfs

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: true

      - name: Init build environment
        run: |
          if [ -n "${{ inputs.init-build-script }}" ]; then
            ./"${{ inputs.init-build-script }}"
          fi

      - name: Build snap
        uses: canonical/action-build@v1

      - name: Publish snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.store-credentials }}     
        run: |
          channel="${{ inputs.publish-channel }}"
          echo -e "Channel:\n\t$channel"

          snap_file="$(ls *.snap)"
          snap_size=$(du -h "$snap_file" | cut -f1)
          echo -e "Snap file:\n\t$snap_file $snap_size"

          # Build components argument list
          component_args=()
          echo "Snap components:"
          for comp_file in *.comp; do
              comp_size=$(du -h "$comp_file" | cut -f1)

              # Component file name patterns:
              # <snap_name>+<comp_name>_<comp_version>.comp
              # <snap_name>+<comp_name>.comp
              comp_name=$(echo "$comp_file" | 
                  cut -d'+' -f2 | # drop snap name
                  cut -d'.' -f1 | # drop file extension
                  cut -d'_' -f1) # split by _, take 1st part

              echo -e "\t$comp_file $comp_size"

              component_args+=(--component "$comp_name=$comp_file")
          done

          echo -e "\nUploading snap..."
          set -x
          snapcraft upload "$snap_file" "${component_args[@]}" --release="$channel"
