name: Remove label

on:
  workflow_call:
    inputs:
      label:
        description: The name of the label that gets removed
        required: true
        type: string

jobs:
  remove-label:
    name: Remove label
    if: github.event.label.name == inputs.label
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo as the gh cli needs it for context
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Remove label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr edit $PR_NUMBER --remove-label "${{ inputs.label }}"
