name: Trigger workflow by label

on:
  workflow_call:

jobs:
  trigger:
    name: Trigger workflow and remove label
    if: github.event.label.name == 'trigger-build'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # needed to comment on PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        # Need to check out the repo as the gh cli needs it for context

      - name: Remove 'trigger-build' label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr edit $PR_NUMBER --remove-label "trigger-build"
